#ifndef NW_SND_FX_PARAM_H_
#define NW_SND_FX_PARAM_H_

#include <nw/types.h>

#ifdef NW_PLATFORM_CAFE
  #include <cafe/axfx.h>
#else
  #error
#endif

namespace nw { namespace snd {

enum FxReverbEarlyReflectionMode
{
    FX_REVERB_EARLY_REFLECTION_5MS  = AXFX_REVERBHI_EXP_EARLY_MODE_5MS,
    FX_REVERB_EARLY_REFLECTION_10MS = AXFX_REVERBHI_EXP_EARLY_MODE_10MS,
    FX_REVERB_EARLY_REFLECTION_15MS = AXFX_REVERBHI_EXP_EARLY_MODE_15MS,
    FX_REVERB_EARLY_REFLECTION_20MS = AXFX_REVERBHI_EXP_EARLY_MODE_20MS,
    FX_REVERB_EARLY_REFLECTION_25MS = AXFX_REVERBHI_EXP_EARLY_MODE_25MS,
    FX_REVERB_EARLY_REFLECTION_30MS = AXFX_REVERBHI_EXP_EARLY_MODE_30MS,
    FX_REVERB_EARLY_REFLECTION_35MS = AXFX_REVERBHI_EXP_EARLY_MODE_35MS,
    FX_REVERB_EARLY_REFLECTION_40MS = AXFX_REVERBHI_EXP_EARLY_MODE_40MS
};

enum FxReverbFusedMode
{
    FX_REVERB_FUSED_OLD_AXFX    = AXFX_REVERBHI_EXP_FUSED_MODE_OLD_AXFX,
    FX_REVERB_FUSED_METAL_TANK  = AXFX_REVERBHI_EXP_FUSED_MODE_METAL_TANK,
    FX_REVERB_FUSED_SMALL_ROOM  = AXFX_REVERBHI_EXP_FUSED_MODE_SMALL_ROOM,
    FX_REVERB_FUSED_LARGE_ROOM  = AXFX_REVERBHI_EXP_FUSED_MODE_LARGE_ROOM,
    FX_REVERB_FUSED_HALL        = AXFX_REVERBHI_EXP_FUSED_MODE_HALL,
    FX_REVERB_FUSED_CAVERNOUS   = AXFX_REVERBHI_EXP_FUSED_MODE_CAVERNOUS
};

} } // namespace nw::snd

#endif // NW_SND_FX_PARAM_H_
